name: Keep GitHub Active

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12 PM UTC
  workflow_dispatch:

jobs:
  update_activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a commit
        run: |
          echo "$(date)" >> activity_log.txt
          git config --global user.name "ravyt3ja"  
          git config --global user.email "ravyteja@gmail.com" 
          git add activity_log.txt
          git commit -m "Daily activity update"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ravyt3ja/ravi.git
